name: CI
on: [pull_request]

jobs:
  beefore:
    name: Pre-test checks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        task: ['pycodestyle']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install git+https://github.com/beeware/beefore.git@pr-comments
    - name: Run Beefore checks
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_SHA: $(cut -d' ' -f3 <<< $(git rev-list --parents -n 1 HEAD))
      run: |
        echo $(git rev-parse HEAD^)
        echo ${{ github.sha }}
        echo ${{ github.head_ref }}
        echo $PR_SHA
        beefore --username brutusthebee --repository ${{ github.repository }} --pull-request $(cut -d'/' -f3 <<< ${{ github.ref }}) --commit $PR_SHA ${{ matrix.task }} .

  smoke:
    name: Smoke test
    needs: beefore
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -e .
    - name: Test
      run: |
        python setup.py test

  python-versions:
    name: Python compatibility test
    needs: smoke
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -e .
    - name: Test
      run: |
        python setup.py test
